//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTI.Modules.ReportCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTI.Modules.ReportCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlueButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlueButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Custom Reports.
        /// </summary>
        internal static string CustomReports {
            get {
                return ResourceManager.GetString("CustomReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to your custom reports have not been saved.  Click Yes to save or No to ignore and save later..
        /// </summary>
        internal static string CustomReportsNotSaved {
            get {
                return ResourceManager.GetString("CustomReportsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}..
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to properly download the report {0} from the server..
        /// </summary>
        internal static string errorDownloadFailure {
            get {
                return ResourceManager.GetString("errorDownloadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get data.
        /// </summary>
        internal static string errorFailedToGetData {
            get {
                return ResourceManager.GetString("errorFailedToGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save data back to server.
        /// </summary>
        internal static string errorFailedToSaveToServer {
            get {
                return ResourceManager.GetString("errorFailedToSaveToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;GetReportMessage&apos; Server Message returned Error. No Report returned..
        /// </summary>
        internal static string errorGetReportServerMsg {
            get {
                return ResourceManager.GetString("errorGetReportServerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get data from server.
        /// </summary>
        internal static string errorLoadData {
            get {
                return ResourceManager.GetString("errorLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters between Report and database are mismatched, please contact support team.
        /// </summary>
        internal static string errorNewReportParamter {
            get {
                return ResourceManager.GetString("errorNewReportParamter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Report not found on Server..
        /// </summary>
        internal static string errorNoReport {
            get {
                return ResourceManager.GetString("errorNoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to print. Error:.
        /// </summary>
        internal static string errorPrint {
            get {
                return ResourceManager.GetString("errorPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error, application is being closed now.
        /// </summary>
        internal static string errorStart {
            get {
                return ResourceManager.GetString("errorStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string infoAll {
            get {
                return ResourceManager.GetString("infoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking reports..
        /// </summary>
        internal static string infoCheckingReports {
            get {
                return ResourceManager.GetString("infoCheckingReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum of {0} custom reports has already been reached..
        /// </summary>
        internal static string infoCustomerTypeLimit {
            get {
                return ResourceManager.GetString("infoCustomerTypeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        internal static string infoEndDate {
            get {
                return ResourceManager.GetString("infoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Player.
        /// </summary>
        internal static string infoFindPlayer {
            get {
                return ResourceManager.GetString("infoFindPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Staff.
        /// </summary>
        internal static string infoFindStaff {
            get {
                return ResourceManager.GetString("infoFindStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or Group name contain invalid characters..
        /// </summary>
        internal static string infoNameInvalid {
            get {
                return ResourceManager.GetString("infoNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or Group name cannot be blank..
        /// </summary>
        internal static string infoNameNotNull {
            get {
                return ResourceManager.GetString("infoNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportGroup.
        /// </summary>
        internal static string infoNewGroupDefaultValue {
            get {
                return ResourceManager.GetString("infoNewGroupDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type a new group name.
        /// </summary>
        internal static string infoNewGroupPrompt {
            get {
                return ResourceManager.GetString("infoNewGroupPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Report Group.
        /// </summary>
        internal static string infoNewGroupTitle {
            get {
                return ResourceManager.GetString("infoNewGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportType.
        /// </summary>
        internal static string infoNewTypeDefaultValue {
            get {
                return ResourceManager.GetString("infoNewTypeDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new type name (15 characters max.).
        /// </summary>
        internal static string infoNewTypePrompt {
            get {
                return ResourceManager.GetString("infoNewTypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Report Type.
        /// </summary>
        internal static string infoNewTypeTitle {
            get {
                return ResourceManager.GetString("infoNewTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No person has been found.
        /// </summary>
        internal static string infoNoPeronFound {
            get {
                return ResourceManager.GetString("infoNoPeronFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player:.
        /// </summary>
        internal static string infoPlayer {
            get {
                return ResourceManager.GetString("infoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff:.
        /// </summary>
        internal static string infoStaff {
            get {
                return ResourceManager.GetString("infoStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        internal static string infoStartDate {
            get {
                return ResourceManager.GetString("infoStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine: .
        /// </summary>
        internal static string MachineText {
            get {
                return ResourceManager.GetString("MachineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: .
        /// </summary>
        internal static string PlayerText {
            get {
                return ResourceManager.GetString("PlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PleaseWait {
            get {
                object obj = ResourceManager.GetObject("PleaseWait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Balances.
        /// </summary>
        internal static string report_1 {
            get {
                return ResourceManager.GetString("report_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Liability.
        /// </summary>
        internal static string report_10 {
            get {
                return ResourceManager.GetString("report_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales By Device.
        /// </summary>
        internal static string report_11 {
            get {
                return ResourceManager.GetString("report_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Register Closing Report.
        /// </summary>
        internal static string report_12 {
            get {
                return ResourceManager.GetString("report_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Register Detail Report.
        /// </summary>
        internal static string report_13 {
            get {
                return ResourceManager.GetString("report_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Totals.
        /// </summary>
        internal static string report_14 {
            get {
                return ResourceManager.GetString("report_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winners Report.
        /// </summary>
        internal static string report_15 {
            get {
                return ResourceManager.GetString("report_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Ball Call.
        /// </summary>
        internal static string report_2 {
            get {
                return ResourceManager.GetString("report_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronis Sales By Device.
        /// </summary>
        internal static string report_3 {
            get {
                return ResourceManager.GetString("report_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Inventory.
        /// </summary>
        internal static string report_4 {
            get {
                return ResourceManager.GetString("report_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Status.
        /// </summary>
        internal static string report_5 {
            get {
                return ResourceManager.GetString("report_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Staff.
        /// </summary>
        internal static string report_6 {
            get {
                return ResourceManager.GetString("report_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player List.
        /// </summary>
        internal static string report_7 {
            get {
                return ResourceManager.GetString("report_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Loyalty List.
        /// </summary>
        internal static string report_8 {
            get {
                return ResourceManager.GetString("report_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Mailing Labels.
        /// </summary>
        internal static string report_9 {
            get {
                return ResourceManager.GetString("report_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Center.
        /// </summary>
        internal static string report_center {
            get {
                return ResourceManager.GetString("report_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Report.
        /// </summary>
        internal static string report_UnknowID {
            get {
                return ResourceManager.GetString("report_UnknowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Info for &apos;{0}&apos; is missing on the server..
        /// </summary>
        internal static string reportIsMissing {
            get {
                return ResourceManager.GetString("reportIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Reports {
            get {
                object obj = ResourceManager.GetObject("Reports", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressives.
        /// </summary>
        internal static string reportType_Accruals {
            get {
                return ResourceManager.GetString("reportType_Accruals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bingo.
        /// </summary>
        internal static string reportType_Bingo {
            get {
                return ResourceManager.GetString("reportType_Bingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon.
        /// </summary>
        internal static string reportType_Coupon {
            get {
                return ResourceManager.GetString("reportType_Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string reportType_Electronics {
            get {
                return ResourceManager.GetString("reportType_Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        internal static string reportType_Exceptions {
            get {
                return ResourceManager.GetString("reportType_Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming.
        /// </summary>
        internal static string reportType_Gaming {
            get {
                return ResourceManager.GetString("reportType_Gaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string reportType_Inventory {
            get {
                return ResourceManager.GetString("reportType_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string reportType_Misc {
            get {
                return ResourceManager.GetString("reportType_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        internal static string reportType_Paper {
            get {
                return ResourceManager.GetString("reportType_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payouts.
        /// </summary>
        internal static string reportType_Payouts {
            get {
                return ResourceManager.GetString("reportType_Payouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string reportType_Players {
            get {
                return ResourceManager.GetString("reportType_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string reportType_POS {
            get {
                return ResourceManager.GetString("reportType_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string reportType_Sales {
            get {
                return ResourceManager.GetString("reportType_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string reportType_Staff {
            get {
                return ResourceManager.GetString("reportType_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texas.
        /// </summary>
        internal static string reportType_Texas {
            get {
                return ResourceManager.GetString("reportType_Texas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bingo.
        /// </summary>
        internal static string reportTypeBingo {
            get {
                return ResourceManager.GetString("reportTypeBingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string reportTypeElectronics {
            get {
                return ResourceManager.GetString("reportTypeElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        internal static string reportTypeExceptioins {
            get {
                return ResourceManager.GetString("reportTypeExceptioins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string reportTypeMisc {
            get {
                return ResourceManager.GetString("reportTypeMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string reportTypePlayers {
            get {
                return ResourceManager.GetString("reportTypePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines.
        /// </summary>
        internal static string reportTypePlayersMachine {
            get {
                return ResourceManager.GetString("reportTypePlayersMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string reportTypeSales {
            get {
                return ResourceManager.GetString("reportTypeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string reportTypeStaff {
            get {
                return ResourceManager.GetString("reportTypeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving this machine&apos;s information..
        /// </summary>
        internal static string splashInfoLoadStationSettings {
            get {
                return ResourceManager.GetString("splashInfoLoadStationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Player.
        /// </summary>
        internal static string titleSearchPlayer {
            get {
                return ResourceManager.GetString("titleSearchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Staff.
        /// </summary>
        internal static string titleSearchStaff {
            get {
                return ResourceManager.GetString("titleSearchStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Waiting {
            get {
                object obj = ResourceManager.GetObject("Waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
